server:
  port: 8088
spring:
  datasource:
    url: jdbc.mysql://127.0.0.1:3306/mozhe
    username: root
    password: 123456
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    mode: HTML5
    suffix: .html
    encoding: UTF-8
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
  resources:
    static-locations: classpath:/static/





